[project]
name = "terrain-trails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Ingraham", email = "davingrahamd@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "gpxpy>=1.6.2",
    "manifold3d>=3.2.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "overpy>=0.7",
    "platformdirs>=4.5.0",
    "pyacvd>=0.3.2",
    "pydantic>=2.12.3",
    "rasterio>=1.4.3",
    "scipy>=1.16.3",
    "shapely>=2.1.2",
    "tqdm>=4.67.1",
    "triangle>=20250106",
    "trimesh>=4.9.0",
]

[project.scripts]
terrain-trails = "terrain_trails:main"

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"
